version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ORACLE_HOST=oracle
      - ORACLE_PORT=1521
      - ORACLE_SERVICE=ORCL
      - ORACLE_USER=sys
      - ORACLE_PASSWORD=Oracle123!
    depends_on:
      - oracle
    networks:
      - vuln-net

  oracle:
    image: gvenzl/oracle-xe:21-slim
    environment:
      - ORACLE_PASSWORD=Oracle123!
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vuln-net

networks:
  vuln-net:
    driver: bridge

volumes:
  oracle-data: